### ISSUE TITLE
Add possibility to check/uncheck checkbox-item from rst file

### ISSUE THREAD

**Issue by Letme** [melexis/sphinx-traceability-extension#139]
This should be valid only in that RST file. For example instead of review in Merge Request/Pull Request review is done in meeting and the meeting minutes are put into `meeting-minutes-date.rst` file. Then in that meeting we went over several checklists and those should take precedence (preferably for that file only, although this is up for discussion @dryodon ) over the checkboxes in `merge_request_id`. 

One of the ideas was that we produce a `checkbox-result` directive for meeting minutes which would look something like:
```
.. item:: SLUG_OF_MEETING_MINUTES_NOTES Meeting minutes from review meeting 1st January 2019

    Participants in the meeting bla, yah, hura. 

.. checkbox-result:: SLUG_OF_CHECKBOX-ITEM Answer
    :reviewed_in: SLUG_OF_MEETING_MINUTES_NOTES

.. item-attributes-matrix::
    :filter: SLUG_OF_CHECKBOX-
    :attributes: checked
```

**Comment by Letme** [comment]
That last part of `item-attribute-matrix::` is not needed in this rst file, as that matrix will be in the `checklist.rst` anyway. So we do not need it here and that also kinda voids the file-only request over several checklists but just that we swap number in `merge_request_id` with a filename (`.rst`).

**Comment by JasperCraeghs** [comment]
Would  `SLUG_OF_CHECKBOX-ITEM` need to be present in an MR description as a checklist item? I.e. should the plugin issue a warning when it can't be found in a GitLab/GitHub query?

**Comment by JasperCraeghs** [comment]
After discussion we decided that this feature is an alternative to a checklist in a merge/pull request description. That means that the items in checklist-item directive  don't need to exist in such a checklist.
