### ISSUE TITLE
KeyError: 'checklist_item_regex'

### ISSUE THREAD

**Issue by mwnaumann** [melexis/sphinx-traceability-extension#142]
I am using python3 and just upgraded to the latest version of mlx.traceability.  My document used to build without error.  Now, I am seeing this failure:

...
File "/usr/local/lib/python3.7/dist-packages/mlx/traceability.py", line 186, in process_item_nodes
    regex = app.config.traceability_checklist['checklist_item_regex']
KeyError: 'checklist_item_regex'

Here is the associated log file:

# Sphinx version: 2.2.0
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   assembling single document...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.0) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.8) from /usr/lib/python3/dist-packages/alabaster/__init__.py
#   sphinx.ext.todo (2.2.0) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (2.2.0) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/coverage.py
#   sphinx.ext.ifconfig (2.2.0) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.viewcode (2.2.0) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/viewcode.py
#   matplotlib.sphinxext.plot_directive (3.1.1) from /usr/local/lib/python3.7/dist-packages/matplotlib/sphinxext/plot_directive.py
#   sphinx.ext.autodoc (2.2.0) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (2.2.0) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/doctest.py
#   sphinx.ext.graphviz (2.2.0) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/graphviz.py
#   sphinx.ext.inheritance_diagram (2.2.0) from /usr/local/lib/python3.7/dist-packages/sphinx/ext/inheritance_diagram.py
#   mlx.traceability (unknown version) from /usr/local/lib/python3.7/dist-packages/mlx/traceability.py
#   sphinxcontrib.plantuml (unknown version) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/plantuml.py
#   sphinxcontrib.programoutput (unknown version) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/programoutput/__init__.py
#   sphinxcontrib.wavedrom (unknown version) from /usr/local/lib/python3.7/dist-packages/sphinxcontrib/wavedrom.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.7/dist-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.7/dist-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(['__all__'], to_build)
  File "/usr/local/lib/python3.7/dist-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.7/dist-packages/sphinx/builders/singlehtml.py", line 159, in write
    doctree = self.assemble_doctree()
  File "/usr/local/lib/python3.7/dist-packages/sphinx/builders/singlehtml.py", line 83, in assemble_doctree
    self.env.resolve_references(tree, master, self)
  File "/usr/local/lib/python3.7/dist-packages/sphinx/environment/__init__.py", line 574, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/usr/local/lib/python3.7/dist-packages/sphinx/environment/__init__.py", line 591, in apply_post_transforms
    self.events.emit('doctree-resolved', doctree, docname)
  File "/usr/local/lib/python3.7/dist-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/usr/local/lib/python3.7/dist-packages/mlx/traceability.py", line 186, in process_item_nodes
    regex = app.config.traceability_checklist['checklist_item_regex']
KeyError: 'checklist_item_regex'

**Comment by JasperCraeghs** [comment]
Thank you for reporting! If you are not using the new `checkbox-result` directive, you can downgrade to `mlx.traceability==4.0.0` for an immediate workaround. I will investigate further and release a fix asap.

**Comment by Letme** [comment]
This is related to changes introduced in #140 so make sure you add `checklist_item_regex`  to your `conf.py`. Check `doc/conf.py` for the example.

I do agree we would have to make it more backwards compatible.

**Comment by mwnaumann** [comment]
* this is required by mlx.traceability, version 4.1.0.
* See issue #142

From the example that you referenced, I cut some code and added the following into my conf.py:
`
from decouple import config

traceability_checklist = {
    'private_token': config('PRIVATE_TOKEN', ''),
    'api_host_name': config('API_HOST_NAME', 'https://api.github.com'),
    'project_id': config('PROJECT_ID', 'melexis/sphinx-traceability-extension'),
    'merge_request_id': config('MERGE_REQUEST_ID', '121,138'),
    'checklist_item_regex': r"[A-Z\d_\-]+",
    'attribute_name': config('ATTRIBUTE_NAME', 'checked'),
    'attribute_to_str': config('ATTRIBUTE_TO_STRING', 'Answer'),
    'attribute_values': config('ATTRIBUTE_VALUES', 'yes,no'),
}
`

I'm able to build my document again, but I'm getting some strange warnings:

`WARNING: List item 'QUE-UNIT_TESTS' in merge/pull request 121 is not defined as a checklist-item.
WARNING: List item 'QUE-PACKAGE_TEST' in merge/pull request 121 is not defined as a checklist-item.
WARNING: List item 'QUE-DOCUMENTATION' in merge/pull request 121 is not defined as a checklist-item.
WARNING: List item 'QUE-PROCESS' in merge/pull request 121 is not defined as a checklist-item.
WARNING: List item 'CL-SOME_ITEM' in merge/pull request 138 is not defined as a checklist-item.
WARNING: List item 'CL-ANOTHER_ONE' in merge/pull request 138 is not defined as a checklist-item.
WARNING: List item 'CL-UNDEFINED_CL_ITEM' in merge/pull request 138 is not defined as a checklist-item.`

**Comment by Letme** [comment]
OK, great that you can build. I think the checklist feature is a bit too new and needs a bit more tweaking to make it play nicer and I hope #143 will solve that.


The warnings you are now getting are because you are in fact pinging github.com/melexismelexis/sphinx-traceability-extension pull requests 121 and 138 for the results of checklist-item and because in your documentation you do not have that items defined (logically) the warning is triggered (that is expected). You can try to remove the `merge_request_id` to make it empty string, so `traceability_checklist` should look like (with eliminating dependency on python-decouple):
```
traceability_checklist = {
'private_token': '',
'api_host_name': '',
'project_id': '',
'merge_request_id': '',
'checklist_item_regex': r"[A-Z\d_-]+",
'attribute_name': 'checked',
'attribute_to_str': 'Answer',
'attribute_values': 'yes,no',
}
```
but this probably still needs some testing to see how it would behave (you can help with a quick test).

**Comment by Letme** [comment]
I think release 4.1.1 is solving your issues. Also readme was updated a bit.
