### ISSUE TITLE
Custom item attributes are overlapping matrix filters

### ISSUE THREAD

**Issue by sannenj** [melexis/sphinx-traceability-extension#148]
We recently added a new custom item attribute named "source".
This seemed to work just fine at first glance. However it turns out that it influences the generation of e.g. an item-matrix. The reason seems to be that the item-matrix also contains an "attribute" called "source" that is used to filter the source end of a relation. 

This resulted in an always-empty matrix and no warning or error being produced.
For now I have worked around the issue by renaming the custom item attribute.

Would it be possible to limit the scope of the custom attributes to items only? Or alternatively produce a diagnostic in order to detect this issue?

Thank you!

**Comment by JasperCraeghs** [comment]
I agree that this is an issue and I opened a PR that will do the following: A warning will be produced that indicates in which directive(s) the overlap occurs. In case of overlap your custom attribute definition will be ignored in the aforementioned directive(s), i.e. the directive option has priority. The behavior of non-overlapping custom attributes remains unchanged.
