### ISSUE TITLE
Add attribute sorting for items

### ISSUE THREAD

**Issue by pietvr** [melexis/sphinx-traceability-extension#160]
When adding items with a lot of attributes the default alphabetical sort is not always ok.

A sorting attribute would address this like:

```
.. item:: FMEA_FUNCTION_SYSTEM The system must work
    :attribute_sort: action status 
    :action: We will make the system work
    :status: approved
```

The ones not mentioned could be left  alphabetical after the ones mentioned

**Comment by Letme** [comment]
Maybe better would be to provide a blank directive where you would have 

```
.. attribute-sort::
    :item_regex: FMEA_
    :attribute_sort: list attributes space separated
```

so that we do not have to apply sorting attribute per each item.
