### ISSUE TITLE
Multi-column item-matrix

### ISSUE THREAD

**Issue by bavovanachte** [melexis/sphinx-traceability-extension#165]
For traceability matrix use cases, it would be useful to create a multi-column item-matrix. 

Software requirement | Unit test case | Integration test case | Application test case 
-- | -- | -- | --
SWRQT-PWM | UTEST-PWM | ITEST-PWM | ATEST-PWM |
SWRQT-I2C |  | ITEST-I2C | ATEST-I2C |
SWRQT-ADC | UTEST-ADC | | ATEST-ADC |
SWRQT-DSP |  | ITEST-DSP | |
SWRQT-UNTESTED | 

The coverage could still give 80% (only 1 requirement that has no match in any of the 3 columns). An individual coverage per column could be interesting as well, but not for our specific usecase (we don't expect any test category to attain 100% coverage)

What triggered this feature request for us is the application in FMEA. In order to assign the scores, it's important to be able to quickly see at which levels a specific feature is tested. As there are often a lot of features to cover in this analysis, it would be useful to get this information directly from a single table, rather than having to open each requirement separately.

Thoughts?

**Comment by JasperCraeghs** [comment]
This looks like it could be useful indeed! Do you think we can simply extend the `item-matrix` so it can handle more than one argument for the `:target:` option?

**Comment by bavovanachte** [comment]
Seems perfectly reasonable to me!

**Comment by bavovanachte** [comment]
Done in #178
