### ISSUE TITLE
Feature request: Add possibility to filter on type using AND logic

### ISSUE THREAD

**Issue by Letme** [melexis/sphinx-traceability-extension#194]
Enable filtering source/target items in matrix by using special attribute, which would filter items (using AND) displayed in matrix that have more than one relation (type) present in source, but not necessary against `:target:` item.

For example:
 - Item A `is parent` to Item B
 - Item A `is related` to Item C
 - Item AD `is parent` of Item B
 - Item AF `is related` to Item C
 - Item AE `is parent` to Item G
 - Item AE `is related` to item H

Matrix with `source` matching all `Item A*` items, target matching all `Item B*` regex and `types`: `is parent` and `is related` should only display Item A with Item B link. 

How this would go: As existing behavior, first source and target filter out the C, G, H items, so AD and A remain. Then, the new type attribute is applied which filters out AD (because it is missing `is_related` type to anything). So, the only remaining line that matches all conditions is printed **Item A `is parent` to Item B**.

**Comment by JasperCraeghs** [comment]
What you want is an additional option for the item-matrix directive, called *hasrelation* for example, like so: `:hasrelation: is_related`. It is an additional filter for source items and has nothing to do with the `:target:` option.
