### ISSUE TITLE
Link targets via intermediate items in item-matrix

### ISSUE THREAD

**Issue by pietvr** [melexis/sphinx-traceability-extension#199]
When this is available any table can be presented with a given set of intermediate item and (defined) relations.

**Comment by JasperCraeghs** [comment]
Let me clarify this feature request with an example:

Let's say we have DESIGN-, RQT-, and TEST- items and we want to generate an item-matrix with DESIGN-items as `:source:` and TEST-items as `:target:`. These source and target items are not directly linked to each other. They are linked via the intermediate RQT-items:

DESIGN -_fulfills_-> RQT -_validated_by_-> TEST

Let's extend the directive with a new option `:intermediate:` and allow extension of the `:type:` option, separating relationships between source-intermediate and intermediate-target with a `|` character.
```
.. item-matrix::
    :source: DESIGN-
    :intermediate: RQT-
    :target: TEST-
    :type: fulfills | validated_by
```

**Comment by JasperCraeghs** [comment]
If the `:intermediate:` option is used, the `:type:` option shall also be used and contain at least two relationships, separated by a `|` character. 

I think we can live with this restriction. This restriction allows a cleaner implementation, which will result in faster processing of the directive.

**Comment by Letme** [comment]
I like the suggestion. 2 or more for the type. If there are not two in type, then please output a warning. I assume we also do not want to check if they are equal...

**Comment by JasperCraeghs** [comment]
> I assume we also do not want to check if they are equal...

The relationships passed to the type option are allowed to be equal.

> I like the suggestion. 2 or more for the type. If there are not two in type, then please output a warning. I assume we also do not want to check if they are equal...

The relationships passed to the type option are allowed to be equal.
