### ISSUE TITLE
Warnings don't display line number information

### ISSUE THREAD

**Issue by bavovanachte** [melexis/sphinx-traceability-extension#2]
An example warning is as follows:

sample_file.rst:None: WARNING: Traceability: cannot link to RQT-TEST-1234, item is not defined

It would be useful to have the line number included in the warning.

**Comment by SteinHeselmans** [comment]
After #3 remaining

- investigate if we can include linenumbers even on warnings from docutils.node stuff

- use warnings plugin to assert the number of warnings in example build
