### ISSUE TITLE
Create hybrid between item-matrix and item-attributes-matrix

### ISSUE THREAD

**Issue by JasperCraeghs** [melexis/sphinx-traceability-extension#224]
I want a matrix that can show attributes of source items, linked target items and the attribute of the target items.
```
.. hybrid-matrix:: 
    :source: <<regex>>
    :target: <<regex>>
    :type: <<relationships>>
    :sourceattributes:  <<attributes>>
    :targetattributes: <<attributes>>
    :hidetarget:
    :nocaptions:
    :onlycaptions:
```

Or do you think we should extend an existing directive? @Letme

**Comment by Letme** [comment]
I have a feeling that extending the existing directive will be more user friendly. How do you see this visualized since it is 4 items - as that would help us decide which directive to extend.

**Comment by JasperCraeghs** [comment]
You can look at it as an `item-matrix` with attribute(s) of source items and/or target items included and the option to hide the target(s). 
You can also look at it as an `item-attributes-matrix` with support for nesting via target(s) and the option to show the target(s).

I believe it will be easier and more user friendly to extend the `item-matrix` directive compared to the `item-attributes-matrix`.

> How do you see this visualized since it is 4 items

What do you mean?

**Comment by Letme** [comment]
Direct discussion it was decided that extending `item-matrix` is more user-friendly and should be implemented. Visualization is the same table but filtered differently according to the attribute(s) in the directive.
