### ISSUE TITLE
Feature request: relink the certain links to another item

### ISSUE THREAD

**Issue by Letme** [melexis/sphinx-traceability-extension#251]
I want an option to relink links to certain items to another items. The example is that when item A is read only and has fixed links to item B, then when item A is reused in another project where item B does not exist, I want possibility to map the link to item B as a link to item C (same link). For this I would propose a new directive `item-relink` which in future could also potentially have an option to change the `link type` as well (`:targettype:`).

```
.. item:: A This is item A and it cannot be modified
    :parent_of: B

.. item:: C This is the target item in project we can modify

.. item-relink::
    :source: B
    :target: C
    :sourcetype: parent_of
```

This would produce equal of:

```
.. item:: A This is item A and was modified within the traceability extension
    :parent_of: C
```

**Comment by JasperCraeghs** [comment]
What should happenen when `:target:` has no value? Should the link to the source be removed instead of relinked?

**Comment by Letme** [comment]
it could indeed be like that, but my initial thought would be not to use this feature.
