### ISSUE TITLE
Prepare support for Sphinx 6

### ISSUE THREAD

**Issue by JasperCraeghs** [melexis/sphinx-traceability-extension#281]
This deprecation warning needs to be addressed: `RemovedInSphinx60Warning: The 'app' argument for BuildEnvironment() becomes required now.`

**Comment by JasperCraeghs** [comment]
also keep an eye on https://www.sphinx-doc.org/en/master/changes.html#release-6-0-0-in-development

**Comment by Letme** [comment]
[v9.6.0](https://github.com/melexis/sphinx-traceability-extension/tree/v9.6.0) already supports Sphinx 6
