### ISSUE TITLE
Build requires a lot of memory when there are many items

### ISSUE THREAD

**Issue by Letme** [melexis/sphinx-traceability-extension#282]
We are getting some reports of running out of memory on concurrent runners:

```
Sphinx parallel build error:
OSError: [Errno 12] Cannot allocate memory
make[3]: *** [infra/Make-documentation.mk:607: html] Error 2
```

Are there any quick win optimizations we could do?

**Comment by Letme** [comment]
I did some searching and while python lists are the fastest way to manipulate data, they might grow out of the memory space of the application when too big, resulting in the above mentioned crash. The SQL (probably SQLite) database would solve this problem, although it would slow things down it would also enable to share the database among threads and queries.

**Comment by JasperCraeghs** [comment]
I think that the recursive nature of the item-tree implementation results in the highest memory usage in our internal project's documentation.

Replacing lists by generators where possible will help and may be a good first step for easy gains. 

> [Generators are memory-efficient ways of processing huge datasets. They process the data incrementally and do not allocate memory to all the results at the same time.](https://medium.com/learning-better-ways-of-interpretting-and-using/python-generators-memory-efficient-programming-tool-41f09077353c)
