### ISSUE TITLE
A question on indentation of `.. item::` content

### ISSUE THREAD

**Issue by passeris** [melexis/sphinx-traceability-extension#307]
This question is partially technical but also somewhat process-related. 

How important is the indentation below an `.. item::` declaration (not including the attributes)? For example, both of these examples work just fine when generating html output:

```
.. item:: ID_1 The first item
   :realizes: REQ_1

   This item is indented by 3 spaces.

   .. table:: function table
      :widths: auto
      
      == ===
      H1 H2
      == ===
      1  On
      2  Off
      == ===

.. item:: ID_2 The second item
   :realizes: REQ_2

This item has no indentation.

.. table:: function table
   :widths: auto

   == ===
   H1 H2
   == ===
   1  On
   2  Off
   == ===
```

The reason I ask this question is because recently I tried adding some .csv files with indentation. Sphinx however could not find the .csv files. When I removed the indentation, the files were found and rendered correctly.

I think the first item in the example would be more proper, since everything that describes that item is part of it.

**Comment by Letme** [comment]
The `This item has no indentation.` text is not part of the item. Same for the table. Item is a block command and then needs indented block to put paragraphs together. Number of spaces is not described (can also be 2 - usually python perscribes to 2 or 4 and 8 is in linux kernel). 

That means if you want the text and table to be part of the item, you will need to indent them to keep them as same block.

**Comment by passeris** [comment]
Okay, then the first example is the proper and correct version. The indentation then (in this example 3 spaces) is indeed important, even if it renders correcly in both cases.

Thanks for clarifying

**Comment by Letme** [comment]
2 should not render correctly - it should be text outside of the item (detached from item), which means show/hide arrow on the right side would not collapse the text accordingly. But it also depends a bit on stylesheet and theme how this is displayed. The element tree however in example 2 will not put paragraph under item.

**Comment by Letme** [comment]
You are correct, the attributes are collapsed only, but if you look at HTML, you will see that if you do not indent the content to your item it is not part of the item and that might affect some features in future (if they are not affected now). We also have callback option, which in your case has an empty paragraph (item body), but if you indent it, it allows you to modify item body through it.

**Comment by Letme** [comment]
Maybe callback option is what you would use to fix the include paths - maybe @jce already has experience with including a file in an item (what would be the start path or the item body)

**Comment by JasperCraeghs** [comment]
The content of an item _should_ be indented. There is a visual difference in the rendered output (see [example](file:///home/jce/projects/git/sphinx-traceability-extension/doc/_build/html/integration_test_report.html?highlight=This%20text%20is%20not%20part%20of%20any%20item#r002). Furthermore, proper item bodies can be inspected and modified by the callback functions `traceability_inspect_item` and `traceability_callback_per_item`.

Item bodies are parsed using a different RST parser instance that maybe has a different state/context or doesn't support the full functionality. I suspect that this is why a relative file path could not be resolved by it.

However, while trying an absolute path in `.. csv-table::` with **Sphinx 5.0.0**, I received the following warning: `WARNING: ":file:" option for csv-table directive now recognizes an absolute path as a relative path from source directory. Please update your document.`

Relative paths in `.. csv-table::` in item bodies are supported with Sphinx>=5.x. FYI @bavovanachte

**Comment by passeris** [comment]
I inspected the output of one my specifications that has the correct indentation and see that it is divided by sections (an `.. item::`), followed by several `div` entries. The requirement text itself (`.. item::`) is placed in a `<blockquote>`:

``` html
<section id="...">
...
   <div class="collapsible_links collapse docutils container" id="...">
      <div class="item admonition">
         ...
      </div>
      <dl class = "simple">
         ... attribute information
      </dl>
   </div>
   <blockquote>
      ... content of requirement, design, pictures, text, tables, etc.
   </blockquote>
</section>
```

I'll restructure my documents now to make sure the indentation is correct. This discussion definately helped me understand better what is going on when translating from .rst to .html. Thanks to everyone!
