### ISSUE TITLE
Provide attribute filtering for item-piechart 

### ISSUE THREAD

**Issue by pietvr** [melexis/sphinx-traceability-extension#314]
item-matrix has filtering on attributes

    .. item-matrix:: matrix
        :some_attribute:

Can we have the same for  item-piechart

**Comment by Letme** [comment]
Item-attribute-matrix not what you want?

**Comment by pietvr** [comment]
Item-attribute-matrix has this filtering. We should add the same filtering for item-piechart.

**Comment by JasperCraeghs** [comment]
It has this fuctionality already. https://melexis.github.io/sphinx-traceability-extension/usage.html#pie-chart-of-documentation-items

`<<attribute>>` : optional, single argument

Python-style regular expression used to filter the source items based on their attributes. The attribute value is not used to filter target items. When omitted, no filtering is done on the source item attributes.
