### ISSUE TITLE
Confusing behavior of item-piechart colors argument

### ISSUE THREAD

**Issue by gcrabbe** [melexis/sphinx-traceability-extension#321]
The `colors` argument to the `item-piechart` directive contains some (undocumented) logic to intelligently allocate colors around empty categories, allowing the user to provide fewer color arguments than what's called for in the documentation:

> a color for each regex in id_set, followed by as many relationships/colors given for [...] the \<\<attribute>> option

However, it seems the corresponding logic is not quite correct, as evidenced by the following MRE:

```
.. item:: RQT-1 UNCOVERED

.. item:: RQT-2 COVERED
    :validated_by: TC-2

.. item:: TC-2

.. item:: RQT-3 FAILED
    :validated_by: TC-3

.. item:: TC-3
    :tested_by: TR-3

.. item:: TR-3
    :result: FAILED

.. item:: RQT-4 PASSED
    :validated_by: TC-4

.. item:: TC-4
    :tested_by: TR-4

.. item:: TR-4
    :result: PASSED

.. item-piechart::
    :id_set: RQT- TC- TR-
    :label_set: UNCOVERED, COVERED, EXECUTED
    :sourcetype: validated_by
    :targettype: tested_by
    :result: FAILED, PASSED
    :colors: grey yellow red green
```

In that example, the `EXECUTED` group is empty, as all `TR`s have a `PASSED`/`FAILED` value. One would then expect four color arguments to be sufficient. Attempting to build said MRE, however, will result in the following warning:

```
WARNING: item-piechart contains 4 slices: 1 color(s) will be reused
```

And the following pie chart:

![image](https://user-images.githubusercontent.com/28896839/201902463-ee7f9c65-f2c2-4ce9-85dd-72cbfbde9e73.png)

One could argue that even if the feature worked as expected, the correct number of color arguments should never depend on a category being empty, as that is not necessarily under the user's control (as in the `PASSED`/`FAILED` example above).

**Comment by JasperCraeghs** [comment]
> One could argue that even if the feature worked as expected, the correct number of colors arguments should never depend on a category being empty

I disagree. The feature worked as expected and as documented. In your exampe `red`  is assigned to the label `EXECUTED`. If there is no slice with that label, you won't see a red slice. This way, the assignment of the colors is deterministic, which is crucial in my opinion, i.e. the assignment of colors must not depend on whether some labels are used or not.

The warning message can be improved to mention that for every label a color should be defined even if some labels will never be used.

Do you agree with my reasoning and solution?

**Comment by gcrabbe** [comment]
To clarify things further, as it may not be immediately obvious from my previous example that there *is* a dynamic dependency between the number of color arguments and the number of empty groups, please consider the following MRE. It is mostly the same as the previous one, only removing the `FAILED` result of `TR-3`:

```
.. item:: RQT-1 UNCOVERED
    :scope: SYSTEM

.. item:: RQT-2 COVERED
    :validated_by: TC-2

.. item:: TC-2

.. item:: RQT-3 EXECUTED
    :validated_by: TC-3

.. item:: TC-3
    :tested_by: TR-3

.. item:: TR-3

.. item:: RQT-4 PASSED
    :validated_by: TC-4

.. item:: TC-4
    :tested_by: TR-4

.. item:: TR-4
    :result: PASSED

.. item-piechart::
    :id_set: RQT- TC- TR-
    :label_set: UNCOVERED, COVERED, EXECUTED
    :sourcetype: validated_by
    :targettype: tested_by
    :result: FAILED, PASSED
    :colors: grey yellow red green
```

In that example, the `FAILED` group is empty, as all `TR`s are either empty or have a `PASSED` value. The same four color arguments have been provided. Attempting to build said MRE, however, will not result in any warnings.

We conclude, therefore, that:
1. There is an undocumented dependency between the number of color arguments and whether some groups are empty.
1. Said dependency may cause build warnings to appear or disappear depending on the contents of the traceability database.
1. Said warning messages are entirely unhelpful.

Given the above, and especially item 2, I would argue in favor of just getting rid of that "feature".

**Comment by JasperCraeghs** [comment]
1. The logic behind the behavior that assigns colors to slices isn't documented but the number of colors that *should* be provided is documented:

> By default, matplotlib will choose the colors. This option allows you to define custom colors. You should specify
> a color for each regex in *id_set*, followed by as many relationships/colors given for *sourcetype* option, if
> the *splitsourcetype* flag is used, and the *targettype* option or the *<<attribute>>* option (*:result:* in the
> example).

2. True. #318 addresses this issue. I plan to release this in v10.0.0 soon. Then, a warning will be reported when the right amount of colors have been provided, independent of the contents of the pie chart.

SWCC relies on this behavior and I don't want it to change. It works well.
