### ISSUE TITLE
Effect of attribute-link directive is dependent on order in which files are read

### ISSUE THREAD

**Issue by gcrabbe** [melexis/sphinx-traceability-extension#322]
It seems the evaluation of the `attribute-link` directive is subject to all kind of race conditions w.r.t. traceability directives in other files.

For instance, building the following project (with `sphinx-build -E`, naturally):

```
index
*****

.. toctree::
    aaaaa
    zzzzz

.. item:: RQT-1
    :scope: UNIT

.. item-attributes-matrix::
    :attributes: scope
```
```
aaaaa
*****

.. item:: RQT-2
    :scope: UNIT

.. attribute-link::
    :scope: INTEGRATION
```
```
zzzzz
*****

.. item:: RQT-3
    :scope: UNIT
```

Will result in the expected attribute matrix:

      | Scope
--    | --
RQT-1 | INTEGRATION
RQT-2 | INTEGRATION
RQT-3 | INTEGRATION

However, moving the `attribute-link` directive from `aaaaa.rst` to `zzzzz.rst`:

```
index
*****

.. toctree::
    aaaaa
    zzzzz

.. item:: RQT-1
    :scope: UNIT

.. item-attributes-matrix::
    :attributes: scope
```
```
aaaaa
*****

.. item:: RQT-2
    :scope: UNIT
```
```
zzzzz
*****

.. item:: RQT-3
    :scope: UNIT

.. attribute-link::
    :scope: INTEGRATION
```

Will give a somewhat more disappointing result:

      | Scope
--    | --
RQT-1 | UNIT
RQT-2 | UNIT
RQT-3 | UNIT

Nonetheless, and perhaps more worryingly, `zzzzz.html` reads:

> RQT-3
>
> Attributes
> 
> &nbsp;&nbsp;&nbsp;&nbsp;Scope: INTEGRATION

**Comment by JasperCraeghs** [comment]
Thanks for reporting. This bad behavior existed for the item-link and item-relink directives and was recently fixed. A similar fix should be implemented for the attribute-link directive.
