### ISSUE TITLE
Generic family 'sans-serif' not found because none of the following families were found: Lato

### ISSUE THREAD

**Issue by kravchenkoloznia** [melexis/sphinx-traceability-extension#326]
Adding an `item-piechart` causes the following warning during the sphinx build:

```console
findfont: Generic family 'sans-serif' not found because none of the following families were found: Lato
```

Building in a sphinx docker image: https://hub.docker.com/r/sphinxdoc/sphinx

**Comment by JasperCraeghs** [comment]
What's the issue? Do you want the Lato font as default in pie charts or not? To address this warning, you can install the Lato font: `apt-get install fonts-lato`

**Comment by kravchenkoloznia** [comment]
The issue is that I see the mentioned warning during the build process.
I've tried to install the `fonts-lato` package but it didn't solve the issue.

**Comment by kravchenkoloznia** [comment]
Found a solution.

Option 1:
Run the `rm ~/.cache/matplotlib -rf` command after `apt-get install fonts-lato`.

It can be implemented in the dockerfile as

```docker
FROM sphinxdoc/sphinx

RUN  apt-get update \
     && apt-get install --no-install-recommends -y \
          fonts-lato \
     && apt-get autoremove \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* \
     && rm ~/.cache/matplotlib -rf
```

Option 2:
Upgrade the dependency to `matplotlib` to version `>=3.1.1`. I haven't tested this option but it is mentioned as one of the possible solutions in [this discussion](https://stackoverflow.com/a/58325348/16380558).
