### ISSUE TITLE
multiple warnings when building with `make pdflatex` multiple definitions

### ISSUE THREAD

**Issue by passeris** [melexis/sphinx-traceability-extension#331]
I get a warning when building the latex version of the documentation about multiple definitions of labels like the following:

`LaTeX Warning: Label 'software_components/componentA:req-29972' multiply defined.`

I traced it down to multiple locations where a requirement is _referenced_ using traceability relationships like :realizes: and traceability tables where I show a design element and what requirement it traces to. The requirement is unique, and is not a duplicate. Any realistic use-case will reference the same requirement in multiple locations. Finally, the documentation is fine, and the output is okay and works in html and PDF, but those warnings get in the way of seeing true potential errors. Is there a way around this?

**Comment by JasperCraeghs** [comment]
I remember seeing this warning years ago but not recently. This could be a Sphinx bug that has been fixed in the meantime, see https://github.com/sphinx-doc/sphinx/issues/5325. Which version of Sphinx did you use?
