### ISSUE TITLE
Question on item traceability ot external requirements

### ISSUE THREAD

**Issue by passeris** [melexis/sphinx-traceability-extension#332]
I'm in a situation where our external requirements are located in Jira. In the Jira system, there are REQ-1234 tickets that have an attachment to some PDF or excel sheet that have the requirements. The documents themselves have individual IDs. I am thinking about refering just the Jira ticket ID using something like:

`:ext_requirement: REQ-1234`

However, that just points to the overall document or REQ. Is there a way to show the specific ID I am refering to in the attached document? For example:

```
    :ext_requirement: 
      REQ-29972 ID-45
      REQ-29972 ID-48
      REQ-29972 ID-49
```

In the example above, the hyperlink generated would only be for REQ-29972, and the ABC-56 is just information text, kind of like a caption, that shows the reader where in the document to look once he opens the Jira ticket and the attached .docx, .xls or PDF.

When I try it however, I get something like this in the HTML:

![grafik](https://user-images.githubusercontent.com/94304985/208683636-401ee3ed-8d39-4dd9-abb0-c0d00cfd5edb.png)

What I would like to see (shown in HTML) is the following:
```
<dl class="simple" style="">
<dt>Attributes</dt><dd><p></p><p>ASIL: D</p>
<p></p>
</dd>
<dt>Realizes:</dt><dd><p></p><p><span class="target" id="id-45"></span><a class="reference external" href="https://issue.example.com/browse/REQ-29972">REQ-29972</a> ID-45</p>
<p></p>
</dd>
<dd><p></p><p><span class="target" id="id-48"></span><a class="reference external" href="https://issue.example.com/browse/REQ-29972">REQ-29972</a> ID-48</p>
<p></p>
</dd>
<dd><p></p><p><span class="target" id="id-49"></span><a class="reference external" href="https://issue.example.com/browse/REQ-29972">REQ-29972</a> ID-49</p>
<p></p>
</dd>
<dd><p></p><p><span class="target" id="req-29972"></span><a class="reference external" href="https://issue.example.com/browse/REQ-29972">REQ-29972</a></p>
<p></p>
</dd>
<p></p>
</dd>
</dl>
```

**Comment by Letme** [comment]
I have a feeling you are looking for the traceability_external_relationship_to_url feature?

```
# Additional relationships for traceability plugin
ext_relationships = {
    'ext_robotframeworklog': '',  # for xunit2rst>=1.1.0 with `--links` flag
}
ext_relationship_to_string = {
    'ext_robotframeworklog': 'Details in log file',
}
ext_relationship_to_url = {
    'ext_robotframeworklog': 'field1#field2',
}
traceability_relationships.update(ext_relationships)
traceability_relationship_to_string.update(ext_relationship_to_string)
traceability_external_relationship_to_url.update(ext_relationship_to_url)
```
Where item defined is basically linking to filename and `#id`:
```
.. item:: THE_SOURCE_ITEM
    :ext_robotframeworklog: some_very_custom_log.html:ID-45
```

Or maybe you want it simpler and just use the field1 (since it seems first part is always the same in your example), then you will have `:ext_ REQ-29972: ID-45` - so you list `.pdf` in the ext_relationships and then only apply ID links to it (linking to titles in PDF works with around same principle)

**Comment by passeris** [comment]
Thanks for the answer, that worked perfectly.

It seems that I was close, but the space after `:`was causing problems. When I removed it, it worked fine, generating a link to the Jira ticket using the URL in `traceability_external_relationship_to_url` along with the issue ID. The second field, `field2` is of course ignored, because it is not part of the actual URL but used instead for showing the reader which ID I am referencing.

**Comment by Letme** [comment]
ok, so you discard field2 because in the JIRA ticket you need to manually search for pdf, download it and find the ID. Painful. Glad to help.
