### ISSUE TITLE
Way to customize color for links to items

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/sphinx-traceability-extension#34]
Some users want to customize the color (background/foreground) of a hyperlink to a traceable item, in order to easilty recognize the type of item which is linked to.

A short search in docutils didn't give immediate results, so it might not be possible at all. Investigation needed...

**Comment by JasperCraeghs** [comment]
What do you mean by *type of item*?

**Comment by Letme** [comment]
Type as Test Case, Requirement, etc. We could do this so far with a regex match, but thinking about it we could add additional attribute `:type:` to make a bit more deterministic approach (but it requires a bit more typing).

**Comment by SteinHeselmans** [comment]
we could also define new directives e.g. .. swrqt:: or .. design:: to be used in stead of .. item:: 

These new directives could be added in conf.py of a project, or in the tool itself. Attributes and/or relations (like above :type: example) could be added to these in conf.py through e.g. the callback per item.

**Comment by JasperCraeghs** [comment]
Docutils allows modification of the html `class` attribute of each node. I've paired this with a css-file that is generated based on a new dictionary variably in `conf.py`.
