### ISSUE TITLE
process_item_nodes fails with `for event 'doctree-resolved' threw an exception (exception: 'docname')`

### ISSUE THREAD

**Issue by passeris** [melexis/sphinx-traceability-extension#344]
When rebuilding my project I got a strange error in process_item_nodes where the following showed:

```
[build] Extension error (mlx.traceability):
[build] Handler <function process_item_nodes at 0x00000282F5C044A0> for event 'doctree-resolved' threw an exception (exception: 'docname')
```

The problem is I don't know what change I introduced in such a small file that would have caused an exception especially when it built just fine before. Is there a way to get a more detailed log somewhere?

**Comment by passeris** [comment]
I found the issue. I had forgotten that one of my changes was in the conf.py file. In there I had the following:

`'depends_on': 'impacts_on',`

However, I did not define `impacts_on`, once I added this to `traceability_relationship_to_string` it worked fine:

`'impacts_on': 'Impacts on',`

**Comment by Letme** [comment]
OK, so what we should add is a check that all `relationships` are defined in the `relationship_to_string` dict at the environment initialization (https://github.com/melexis/sphinx-traceability-extension/blob/master/mlx/traceability.py#L319) and output a nicer error than a crash at the doctree-resolved stage.
