### ISSUE TITLE
How do you consider external requirements in `:stats:` calcuation?

### ISSUE THREAD

**Issue by passeris** [melexis/sphinx-traceability-extension#346]
We have a lot of requirements to link to that are external. I have all the URLs for the requirements in the form of a list. If I use this list in a regex expression, the requirements show up fine in a traceability table, but only the ones that are linked using an `ext` traceability relationship. Here is an example traceability table definition:

```
  :source: (REQ-1|REQ-2|REQ-3)
  :target: SWCD
  :sourcetitle: Requirement
  :targettitle: Design
  :nocaptions:
  :stats:
  :type: ext_requirement
  :class: longtable
```

Suppose that REQ-1 is *not* linked, my table will look like this (with 100% coverage on the `stats`):

| Requirement |Design|
|:-------------|:--------|
| REQ-2          |SWCD-8|
| REQ-3          |SWCD-3|

I would like to have the unlinked requirement shown so that I know which requirements are missing links.

| Requirement |Design|
|:-------------|:--------|
| REQ-1 | |
| REQ-2          |     SWCD-8|
| REQ-3          |SWCD-3|

**Comment by Letme** [comment]
`REQ-1` is external requirement, so you do not have it defined or exported as `..item`, but it is purely linked to external system by the conf.py regexp?

We usually export external requirements to items for exactly this reason. And it also helps preserve the snapshot of the baseline that we are then developing against.

**Comment by passeris** [comment]
I did not quite understand the answer. So that means we should declare a listing of `.. item::` that repeat the IDs?

```
.. item:: REQ-1
   :ext_requirement: REQ-1
.. item:: REQ-2
   :ext_requirement: REQ-2
.. item:: REQ-3
   :ext_requirement: REQ-3
```

Then anything linking to it, uses a different relationship like `:realizes:`.

**Comment by Letme** [comment]
For that ext_requirement you use something like this in `conf.py`?:

```
# Additional relationships for traceability plugin
ext_relationships = {
    'ext_requirement: '',
}
ext_relationship_to_string = {
    'ext_requirement: 'External requirement reference',
}
ext_relationship_to_url = {
    'ext_requirement': 'https://someurl_rqts.html#field1',
}
traceability_relationships.update(ext_relationships)
traceability_relationship_to_string.update(ext_relationship_to_string)
traceability_external_relationship_to_url.update(ext_relationship_to_url)
```

Yes, well we add `SYS` prefix (for system) to these items,  but I think you have something different, because that `ext_relationship` in fact cannot create circular relationship.

```
.. item:: SYSRQT-REQ-1
   :ext_requirement: REQ-1
```

We use `:depends_on:` relation as we are then creating `SWRQT-REQ-1` or `DIGRQT-REQ-1` as children.

**Comment by passeris** [comment]
Okay, that solves the problem. I have the conf.py set up for external requirements already, what is missing now is the following, where I add the prefix in order to prevent a circular definition:

```
.. item:: SYSRQT-REQ-1
   :ext_requirement: REQ-1
```

Then anywhere in my design (here a component design example) where I link to a requirement, I use the `realizes` relation:

```
.. item:: SWCD-1
   :realizes: SYSRQT-REQ-1
```

So tracing upwards, it is SWCD -> REQ-1 -> SYSREQ-REQ1

**Comment by passeris** [comment]
I inspected the following lines and found out that my conf.py does *not* have those lines:

```
traceability_relationships.update(ext_relationships)
traceability_relationship_to_string.update(ext_relationship_to_string)
traceability_external_relationship_to_url.update(ext_relationship_to_url)
```

**Comment by Letme** [comment]
But how do you have `:ext_requirement:` defined?

**Comment by passeris** [comment]
Adding those lines failed to import `traceability_config`. It seems that is an organizational file for Melixis of some sort.

My `ext_requirement` definition seems to work fine, but I wanted to make sure I have things properly configured. Here is a snippet of each section where `ext_requirement` is referenced (I am using a placeholder URL for demonstration purposes only):

```
ext_relationships = {
    'ext_requirement': '',
 
}
ext_relationship_to_string = {
    'ext_requirement': 'External requirement reference',

}
ext_relationship_to_url  = {

    'ext_requirement': 'https://github.com/melexis/sphinx-traceability-extension/issues/field1',



}

```
