### ISSUE TITLE
`:asil:` items not showing up in an `:item-matrix:`

### ISSUE THREAD

**Issue by passeris** [melexis/sphinx-traceability-extension#350]
I have the following defined for a traceability matrix:

```
.. item-matrix:: Softare Architecture Coverage
  :source: SWCD 
  :target: SWDD
  :sourcetitle: Software Architecture
  :targettitle: Software Detailed Design
  :asil: A(D)
  :targetcolumns: asil
  :nocaptions:
  :stats:
  :group: top
  :class: longtable
```

And a typical item declaration is as follows:

```
.. item:: SWDD_PSA_SRV_Psm_Safety_Init
    :asil: A(D)
    :depends_on:
      SWCD_PSA_SRV_Psm_Safety_Init
  ```
and

```
.. item:: SWCD_PSA_SRV_Psm_Safety_Init
   :implementation_status: implemented
   :allocation: VCPU
   :asil: A(D)
   :realizes: 
    SwSRS_12280
```

Despite both having the attribute `:asil:` properly set, nothing shows up in the traceability table. Any idea why? According to the [documentation](https://melexis.github.io/sphinx-traceability-extension/usage.html#traceability-matrix-of-documentation-items), this should be possible. An example is given where `:status:` is used to filter anything set to `Appr`.

![grafik](https://github.com/melexis/sphinx-traceability-extension/assets/94304985/ed080902-b92e-4271-9acd-5bb303df2a3c)

**Comment by passeris** [comment]
I found the problem. I was not thinking in terms of regex expressions. The value I used was a regex instead of the value I was looking for:

`:asil: A(D)`

That meant I was looking for any `:asil:` attribute that is A, which I have none. All are `A(D)` but I did not have the parentheses escaped like this:

`:asil: A\(D\)`

Once I made that change, it worked.

**Comment by Letme** [comment]
OK, so we can close this?
