### ISSUE TITLE
Can traceability links be suppressed in PDF output?

### ISSUE THREAD

**Issue by passeris** [melexis/sphinx-traceability-extension#351]
Is there a way to supress the display of item traceability links in the PDF version of a build? My document looks okay, but for every item, the links and attributes are fully expanded, which adds to the length of the document.

I would like to have all links collapsed by default just like in the HTML build.

**Comment by JasperCraeghs** [comment]
Yes, see https://melexis.github.io/sphinx-traceability-extension/configuration.html#rendering-of-relationships-per-documentation-object
