### ISSUE TITLE
How do you use a custom config for traceability?

### ISSUE THREAD

**Issue by passeris** [melexis/sphinx-traceability-extension#353]
In the documentation I found this text:

```
sys.path.insert(0, os.path.abspath('<path_to_process_submodule>/config'))

from traceability_config import swcc_traceability_attributes
from traceability_config import swcc_traceability_relationships
from traceability_config import swcc_traceability_relationship_to_string

traceability_attributes = swcc_traceability_attributes
traceability_relationships = swcc_traceability_relationships
traceability_relationship_to_string = swcc_traceability_relationship_to_string
traceability_render_relationship_per_item = False
```

However, I don't know where to store this traceability_config.py file. And if I create one in the root directory of the project, I cannot import the module. I admit, that I have no knowledge of python programming, but I'm wondering how to set this up so we can override traceability relationships.

**Comment by JasperCraeghs** [comment]
We use `sys.path.insert` to add the location of `traceability_config.py` to PATH. Then, we can import `dict` variables that are defined in this Python file.

Our configuration file is located in the `config` directory of our `process` repository, which we add as a GIT submodule to every project, hence `'<path_to_process_submodule>/config'`.

This example code adds the directory `config`, which is located next to `conf.py`, to PATH:
```
import os
import sys
sys.path.insert(1, os.path.abspath('./config'))
```
