### ISSUE TITLE
Scroll position for url link ending with the Id of an Item (anchor/hash)

### ISSUE THREAD

**Issue by LudwigCRON** [melexis/sphinx-traceability-extension#363]
In the case of an URL pointing to a specific section of a page that contains a requirement item / pie-chart / item-matrix (e.g. /html/top/ganymede.html#DIG-RQT-COMP-top-7), the page once loaded is scrolled to an incorrect position.

Instead of displaying the DIG-RQT-COMP-top-7, it will scroll down to the DIG-RQT-COMP-top-24.
The uniqueness of the Id has been ensured.

When the page is refreshed can benefit from the cached position of the different DOM elements, and the browser scrolls to the correct position. In case there are some images and it is slow to fetch the images on the network, the effect is even more pronounced.

Tried on Firefox 120, Firefox 115.4.0esr, Chrome 111.

**Comment by LudwigCRON** [comment]
As a workaround, added a relative filepath to a javascript script inside an `html_js_files` array in the conf.py of the sphinx installation.

In the javascript, I added
```
document.addEventListener("readystatechange", (event) => {
	// DOM is loaded and displayed, position should
	// be computed at this time
	if (document.readyState === "complete") {
	        // delayed the execution due to processing
	        // of large item-matrix, ...
		setTimeout(() => {
			let anchorId = location.hash.slice(1);
			const element = document.getElementById(anchorId);
			element.scrollIntoView({block: "start", inline:"nearest", behavior:"smooth"});
		}, 500);
	}
});

```

**Comment by JasperCraeghs** [comment]
Thank you for opening this issue and providing a possible solution. I will test and integrate your suggestion in the coming days.

**Comment by LudwigCRON** [comment]
You are welcome. The proposed solution is a workaround that seems to work for medium sized item matrix (~200 rqts in a given table). I always arrange myself to have medium sized item-matrices (split into top and per component the requirements). Could be interresting to see the limit.

A possible scenario to look for is to open a link with an anchor into a new tab opened in background. I think this might not work as browsers can have an aggressive throttle strategy for background tabs. And thus delay technique might not be helping.

An other fallback ideas in case of:

1.  use `window.onload` event rather than the readyState variable going to "complete". This event is also generated when all resources are loaded (script executed too?)

2. Register functions that should be executed into an object list that keep the progress. In that case we can rely on a javascript `MutationObserver` to see when to redo scrollIntoView rather than relying on a delay.

Thank you for the support
