### ISSUE TITLE
item-piechart slices should be ordered more logically

### ISSUE THREAD

**Issue by gcrabbe** [melexis/sphinx-traceability-extension#367]
In my project, the following instance of `item-piechart`:
```
.. item-piechart:: Unit requirement pie chart
    :id_set: RQT- TC- TR-
    :label_set: UNCOVERED, COVERED, EXECUTED
    :sourcetype: validated_by
    :targettype: tested_by
    :scope: UNIT
    :result: FAILED, PASSED
    :colors: #b2c4cb #eea320 #b2c4cb #db4140 #65bba9
```

Gives the following pie chart:
![image](https://github.com/melexis/sphinx-traceability-extension/assets/28896839/a0f619e2-f0aa-4d73-9644-e59550cac74d)

I would like to have the "FAILED" slice before the "PASSED" one, so the status "improves" monotonically counterclockwise (UNCOVERED, COVERED, EXECUTED, FAILED, and then PASSED).

I have tried to write:
```
    :result: PASSED, FAILED
```

But this also inverts the result of merging multiple entries, so an item such as this:
![image](https://github.com/melexis/sphinx-traceability-extension/assets/28896839/1480798b-46df-42e1-82ab-6ed01a9627d7)

Will go from "FAILED" (correct) to "PASSED" (incorrect).

My opinion is that the "FAILED" and "PASSED" slices should be ordered the other way around by default to have the same sequencing as the `label_set` attribute, but having it as an option would also be acceptable.

**Comment by JasperCraeghs** [comment]
With configuration `:result: FAILED, PASSED`, PASSED is harder to achieve than FAILED and FAILED is harder to achieve than EXECUTED, etc. From this point of view, it makes sense to take this into consideration while ordering the slices.

However, FAILED has a higher priority than PASSED, so the slices are [currently already ordered by priority](https://github.com/melexis/sphinx-traceability-extension/blob/v11.1.0/mlx/traceability/directives/item_pie_chart_directive.py#L115). Ordering by priority makes less sense than ordering by how hard it is to achieve, so let's tweak the behavior without introducting a new option to the directive.
