### ISSUE TITLE
item-piechart <<attribute>> filtering should give priority to a missing attribute

### ISSUE THREAD

**Issue by gcrabbe** [melexis/sphinx-traceability-extension#369]
In my project, I have the following instance of `item-piechart` (should be familiar by now):
```
.. item-piechart:: Unit requirement pie chart
    :id_set: RQT- TC- TR-
    :label_set: UNCOVERED, COVERED, EXECUTED
    :sourcetype: validated_by
    :targettype: tested_by
    :scope: UNIT
    :result: FAILED, PASSED
    :colors: #b2c4cb #eea320 #b2c4cb #db4140 #65bba9
```

I would have liked the `<<attribute>>` filtering to allow the absence of an attribute to be worse than its presence, so items such as this:
![image](https://github.com/melexis/sphinx-traceability-extension/assets/28896839/3bd9038e-6f33-4870-b197-f7d2cd0d664b)

Could be classified as "EXECUTED" instead of "FAILED", as is currently the case.

**Comment by gcrabbe** [comment]
I would argue in favor of a bug: if that example was "PASSED" instead of "FAILED", the "non-special" configuration would be dangerously misleading.

**Comment by Letme** [comment]
I also think we can treat this as bug based on that last remark - maybe report a warning since `result` should probably have one more argument to specify for the cases where it is not matched?

**Comment by JasperCraeghs** [comment]
> I would have liked the <<attribute>> filtering to allow the absence of an attribute to be worse than its presence, so items such as this:

In your case, the attribute is not absent; its value is an empty string. If the attribute were empty, the behavior would be as you expect. To me, it is strange to have a test report item when the test was not executed. If you would like the plugn to report a warning when the value of  `:result:` is empty, you can configure the attribute like [this](https://github.com/melexis/sphinx-traceability-extension/blob/v11.1.0/mlx/traceability/traceability.py#L509).

**Comment by gcrabbe** [comment]
> In your case, the attribute is not absent; its value is an empty string.

In my example, the `:result:` attribute was actually never defined:

```
.. item:: TR-sim_1 Test record for sim_1

.. item:: TR-sim_2 Test record for sim_2
    :result: PASSED
```

---

> To me, it is strange to have a test report item when the test was not executed.

The test was, in fact, executed, but the test record was malformed.

---

> If you would like the plugin to report a warning when the value of :result: is empty, you can configure the attribute like [this](https://github.com/melexis/sphinx-traceability-extension/blob/v11.1.0/mlx/traceability/traceability.py#L509).

Is it possible to get a warning for the `TR-sim_1` example above?

**Comment by JasperCraeghs** [comment]
Yes. For this, I recommend the use of [`traceability_inspect_item`](https://github.com/melexis/sphinx-traceability-extension/blob/master/doc/conf.py#L390)
