### ISSUE TITLE
Add attribute to item outside of the item definition

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/sphinx-traceability-extension#77]
As with item-link where relations can be added to an item seperate from where they are defined, we can have a (new or extended item-link) directive that allows adding attributes to existing items.

**Comment by JasperCraeghs** [comment]
Do we prefer a new `item-attribute-link` directive or do we extend the `item-link` directive somehow? If so, how can we best extend it? @Letme @bavovanachte

**Comment by JasperCraeghs** [comment]
I'm leaning towards adding a new directive. I think it could be handy to support a regex to filter item IDs rather than only allowing a single item ID.
```
.. attribute-link:: 
    :filter: RQT\\d
    :my_attribute: attribute value
```

**Comment by bavovanachte** [comment]
If we extend it, it will likely result in a very modal interface, right? Something like:

- If you want to add relationships, you have to use it in this mode:

```
      .. item-link::
         :sources: list_of_items
         :targets: list_of_items
         :type: relationship_type
```

- If you want attributes, use it in this mode:

```
      .. item-link::
         :sources: list_of_items
         :attributes: list_of_tuples_with_kv_pairs
```

I'd personally prefer to split into separate directives instead, and I think that's clearer for users as well. As for maintainability of the code: it's probably more maintainable to have 2 small, simple directives than adding complexity to the item-link one to support multiple modes.

**Comment by bavovanachte** [comment]
> I'm leaning towards adding a new directive. I think it could be handy to support a regex to filter item IDs rather than only allowing a single item ID.
> 
> ```
> .. attribute-link:: 
>     :filter: RQT\\d
>     :my_attribute: attribute value
> ```

Good idea. Your proposal allows setting only one attribute pair, right? I understand that we don't need more at the moment, but the need to set multiple attributes may arise in the future. Could we already think of how to extend it in the future without breaking backwards compatibility?

This would work with your current proposal:

```
.. attribute-link:: 
    :filter: RQT\\d
    :my_attribute: attribute value, attribute2 value2
```

**Comment by JasperCraeghs** [comment]
I think you misinterpreted my proposal. Let's say we have an attribute called `status` and we want to set its value to `Approved` for item `RQT-1` only along with setting the `asil` attribute as well:

```
.. attribute-link::
    :filter: RQT-1$
    :asil: C
    :status: Approved
```
