### ISSUE TITLE
Allow hiding (collapsing) the traceability information in an item

### ISSUE THREAD

**Issue by bavovanachte** [melexis/sphinx-traceability-extension#92]
Some items have a lot of other items linked to them. When attempting to read a document (let's say we're reviewing the set of requirements for a given product), this can seriously hinder the readability. 

We could add a small button at the top of the item that allows collapsing the traceability section. In the screenshots below, I added just a clickable "link" that does this (Look at the top for "Hide links")

![image](https://user-images.githubusercontent.com/5442584/60388123-50600300-9aad-11e9-9bdb-75880e37d2f3.png)

After clicking the "button", the item looks like this:

![image](https://user-images.githubusercontent.com/5442584/60388163-cd8b7800-9aad-11e9-8ec2-89bc78e89c3c.png)

Note, I performed these changes manually in the html, not through the plugin (yet). The changes I've made in the html are:

![image](https://user-images.githubusercontent.com/5442584/60388225-99648700-9aae-11e9-93c5-14452b8b1287.png)

And I've added the following code in `traceability.js`:

```js

var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "none") {
        this.innerHTML = "Hide links"
        content.style.display = "block";
    } else {
        this.innerHTML = "Show links"
        content.style.display = "none";
    }
  });
}
```

**Comment by bavovanachte** [comment]
I've tried implementing these changes in the plugin, but ran into a couple of snags:

- Sphinx wouldn't allow me to create a reference node in this way (I'm not sure exactly what the issue was tbh, probably I've missed something silly, but not the biggest issue)
- Can't figure out how to assign an html class (or id) attribute to a sphinx node so that it pops up in the generated html. This class is important in order for the js code to pick up the right "button" and execute the code for it.

Now, I'm sure there are other (simpler?) ways of doing this, or maybe the issues I ran into can be circumvented easily by someone with more experience with Sphinx plugins. I just wanted to lay out the work/investigating I've done so far

**Comment by bavovanachte** [comment]
@SteinHeselmans @Letme @JasperCraeghs Thoughts (maybe about the idea of collapsing the traceability portion first, and actual implementation second)

**Comment by JasperCraeghs** [comment]
I think it is a useful feature to add. About the implementation: I would try to turn the admonition into a button with class='collapsible' instead of creating extra text 'Hide links'.

**Comment by Letme** [comment]
Implementation wise I think there was a problem because all these are not a unique id when generated by sphinx, so you should look more into that (docref) to make some hashes. Otherwise next best thing is to expand all or none. We did that with the item-tree where basically css/javascript closes and opens the tree.

**Comment by SteinHeselmans** [comment]
I checked the result of #115 in the published documentation: works as expected, very good work :+1:
